[package]
name = "http_test"
version = "0.1.0"
edition = "2024"

[dependencies]
http = "1.4.0"
reqwest = "0.13.2"
serde = "1.0.228"
serde_json = "1.0.149"
tokio = {version = "1.49.0", features=["full"]}
